-- MySQL Script generated by MySQL Workbench
-- 11/12/18 23:46:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(64) NOT NULL,
  `group_id` INT NOT NULL,
  `timestamp` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `uid`, `group_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_role_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_role_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_role_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `timestamp` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `parent_id` INT NOT NULL DEFAULT 0,
  `timestamp` INT(11) NOT NULL,
  `company_id` INT NOT NULL,
  `user_group_id` INT NOT NULL,
  `user_group_uid` VARCHAR(64) NOT NULL,
  `user_group_group_id` INT NOT NULL,
  `user_role_group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_group_user_group1_idx` (`user_group_id` ASC, `user_group_uid` ASC, `user_group_group_id` ASC),
  INDEX `fk_group_user_role_group1_idx` (`user_role_group_id` ASC),
  CONSTRAINT `fk_group_user_group1`
    FOREIGN KEY (`user_group_id` , `user_group_uid` , `user_group_group_id`)
    REFERENCES `mydb`.`user_group` (`id` , `uid` , `group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_user_role_group1`
    FOREIGN KEY (`user_role_group_id`)
    REFERENCES `mydb`.`user_role_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `module_id` INT NOT NULL,
  `timestamp` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`module` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `parent_id` INT NOT NULL,
  `level` INT NULL DEFAULT 0,
  `icon` VARCHAR(45) NULL,
  `url` VARCHAR(200) NULL,
  `timstamp` INT(11) NOT NULL,
  `type` INT NOT NULL DEFAULT 1,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_module_permission1_idx` (`permission_id` ASC),
  CONSTRAINT `fk_module_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `mydb`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_role` (
  `int` INT NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(64) NOT NULL,
  `role_id` INT NOT NULL,
  `timestamp` INT(11) NOT NULL,
  `user_role_group_id` INT NOT NULL,
  PRIMARY KEY (`int`),
  UNIQUE INDEX `int_UNIQUE` (`int` ASC),
  INDEX `fk_user_role_user_role_group1_idx` (`user_role_group_id` ASC),
  CONSTRAINT `fk_user_role_user_role_group1`
    FOREIGN KEY (`user_role_group_id`)
    REFERENCES `mydb`.`user_role_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `int` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `timstamp` INT(11) NOT NULL,
  `user_role_int` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`int`),
  UNIQUE INDEX `int_UNIQUE` (`int` ASC),
  INDEX `fk_role_user_role_idx` (`user_role_int` ASC),
  INDEX `fk_role_permission1_idx` (`permission_id` ASC),
  CONSTRAINT `fk_role_user_role`
    FOREIGN KEY (`user_role_int`)
    REFERENCES `mydb`.`user_role` (`int`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `mydb`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `int` INT NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(64) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `salt` VARCHAR(45) NOT NULL,
  `department_id` INT NOT NULL,
  `timestamp` INT(11) NOT NULL,
  `user_role_int` INT NOT NULL,
  `user_group_id` INT NOT NULL,
  `user_group_uid` VARCHAR(64) NOT NULL,
  `user_group_group_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`int`, `uid`, `name`, `company_id`),
  UNIQUE INDEX `int_UNIQUE` (`int` ASC),
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_user_user_role1_idx` (`user_role_int` ASC),
  INDEX `fk_user_user_group1_idx` (`user_group_id` ASC, `user_group_uid` ASC, `user_group_group_id` ASC),
  CONSTRAINT `fk_user_user_role1`
    FOREIGN KEY (`user_role_int`)
    REFERENCES `mydb`.`user_role` (`int`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_user_group1`
    FOREIGN KEY (`user_group_id` , `user_group_uid` , `user_group_group_id`)
    REFERENCES `mydb`.`user_group` (`id` , `uid` , `group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `timstamp` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
